### PR TITLE
Stubbed out CimSession and PSSession operations to use @param syntax …

### PR DESCRIPTION
**Pull request by sean-m**
…to allow operating locally without WinRM

### CODE REVIEW

**Comment by lahell** [comment]
I like this idea, but it needs a lot of work. If I merge this now, the ability to capture on remote computers will be broken. `New-PSSession` is never assigned to the `$PSSession` variable. `New-CimSession` is commented out. `$ETLFilePath` is `$null` when passed to `Get-WinEvent` because it is defined in i different scope. Did you test capture on remote computers after making these changes?

**Comment by s0nders** [comment]
Would also like a switch that indicates running only locally, I manage a lot of environments that block winrm. Currently having to make the same changes @sean-m has made when deploying the module.

**Comment by lahell** [comment]
Thank you for your feedback, @s0nders. WinRM is not needed to capture on local computer, and elevation is not needed to capture on remote computers, but requiring WinRM and elevation for both local and remote capture allowed me to greatly simplify the logic of this function. I mostly use the remote capture and have grown tired of having to open an elevated window, so it is not impossible that I rewrite this function in the future. Requiring WinRM locally is also a potential roadblock for anyone who wants to use [PSDiscoveryProtocol with SCCM](https://github.com/lahell/PSDiscoveryProtocol-SCCM-HWInventory).

**Comment by BornToBeRoot** [comment]
@sean-m @s0nders @lahell Here is new / fully working PR: #12

**Comment by lahell** [comment]
Closing this pull request because merging would break remote capture.

**Pull request closed without merging**
